# Generated by Django 6.0.2 on 2026-02-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('expenses', models.JSONField(default=list)),
                ('token', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
