# Generated by Django 6.0.2 on 2026-02-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
