# Generated by Django 6.0.2 on 2026-02-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='expenses',
            new_name='expenses_ids',
        ),
    ]
