# Generated by Django 6.0.2 on 2026-02-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0005_rename_expenses_user_expenses_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='expenses_ids',
            new_name='expenses_id',
        ),
    ]
