# Generated by Django 6.0.2 on 2026-02-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0006_rename_expenses_ids_user_expenses_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='expenses_id',
            new_name='expense_id',
        ),
    ]
