# Generated by Django 6.0.2 on 2026-02-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0007_rename_expenses_id_user_expense_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='expense_id',
            new_name='expense_ids',
        ),
    ]
