# Generated by Django 6.0.2 on 2026-03-05 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0008_rename_expense_id_user_expense_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_exp',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
